### ISSUE TITLE
Anyone else can provide custom offline-to-online gym-mujoco results? thanks a lot

### ISSUE THREAD

**Issue by alphahumancoder** [corl-team/CORL#11]
As shown in this project, there are large amount offline-to-online results of Antmaze domains, however, lacking gym-mujoco

**Comment by DT6A** [comment]
Hello @alphahumancoder! I remember only https://arxiv.org/abs/2211.11802 paper which was testing offline-to-online on the gym domain. I think the reason why people do not run algorithms there is because it is relatively simple for offline-to-online because we know that online algorithms can learn in those environments while for antmaze and adroit algorithms usually fail to learn anything without using additional data.

You can use CORL codebase to run algorithms on those environments just by setting appropriate hyperparameters and environments of your interest
